Repository MIT-Emerging-Talent/ET6-foundations-group-20, pull requests merged in 2025-01, with the labels that each got.

#40 Closes #16
  solutions/minion_game.py
  solutions/tests/test_minion_game.py
Labels: Challenge

#52 Closes #51
  .markdownlint.yml
  assets/bug-fix.png
  assets/bug.png
  assets/indoor.png
  assets/internal-voluntary-constraints.png
  assets/limited-access.png
  assets/norms-mindmap.png
  assets/outdoor.png
  assets/planning.png
  assets/python.png
  assets/scope.png
  assets/task-planner.png
  collaboration/README.md
  collaboration/communication.md
  collaboration/constraints.md
  collaboration/learning_goals.md
  collaboration/retrospective.md
  notes/README.md
Labels: documentation

#48 Adding solutions
  solutions/count_vowels.py
  solutions/fizz_buzz.py
  solutions/reverse_string.py
  solutions/tests/test_count_vowels.py
  solutions/tests/test_fizz_buzz.py
  solutions/tests/test_reverse_string.py
Labels: documentation, enhancement
